"""NEXUS Tools & Operational Actuators Package."""

from tools.base import BaseTool
from tools.infrastructure_signage import (
    InfrastructureSignageTool,
    SignageUpdateInput,
    SignageUpdateReceipt,
)
from tools.nexus_tools import (
    AmbulanceReservationInput,
    AmbulanceReservationOutput,
    AmbulanceReservationTool,
    AuditLoggingTool,
    AuditLogInput,
    AuditLogOutput,
    GeolocationInput,
    GeolocationOutput,
    GeolocationTool,
    HospitalStatusInput,
    HospitalStatusOutput,
    HospitalStatusTool,
    ImageAnalysisInput,
    ImageAnalysisOutput,
    ImageAnalysisTool,
    IncidentReportsInput,
    IncidentReportsOutput,
    IncidentReportsTool,
    IncidentStatusUpdateInput,
    IncidentStatusUpdateOutput,
    IncidentStatusUpdateTool,
    NotificationInput,
    NotificationOutput,
    NotificationsTool,
    ResourceSearchInput,
    ResourceSearchOutput,
    ResourceSearchTool,
    RoutingInput,
    RoutingOutput,
    RoutingTool,
    WeatherInput,
    WeatherOutput,
    WeatherTool,
    register_all_nexus_tools,
)
from tools.registry import (
    BaseNexusTool,
    ToolError,
    ToolExecutionResult,
    ToolRegistry,
    default_tool_registry,
)
from tools.resource_inventory import (
    ResourceInventoryItem,
    ResourceInventoryTool,
    ResourceQueryInput,
)
from tools.routing_engine import RouteRequest, RouteResult, RoutingEngineTool
from tools.simulated_dispatch import DispatchCommand, DispatchReceipt, SimulatedDispatchTool
from tools.traffic_camera import CameraAnalysisOutput, TrafficCameraInput, TrafficCameraTool
from tools.weather_sensor import SensorReading, WeatherSensorInput, WeatherSensorTool

__all__ = [
    # Legacy / existing tools
    "BaseTool",
    "WeatherSensorTool",
    "WeatherSensorInput",
    "SensorReading",
    "TrafficCameraTool",
    "TrafficCameraInput",
    "CameraAnalysisOutput",
    "RoutingEngineTool",
    "RouteRequest",
    "RouteResult",
    "ResourceInventoryTool",
    "ResourceQueryInput",
    "ResourceInventoryItem",
    "SimulatedDispatchTool",
    "DispatchCommand",
    "DispatchReceipt",
    "InfrastructureSignageTool",
    "SignageUpdateInput",
    "SignageUpdateReceipt",
    # Framework & Registry
    "BaseNexusTool",
    "ToolRegistry",
    "default_tool_registry",
    "ToolExecutionResult",
    "ToolError",
    "register_all_nexus_tools",
    # 11 NEXUS Tools
    "WeatherTool",
    "WeatherInput",
    "WeatherOutput",
    "IncidentReportsTool",
    "IncidentReportsInput",
    "IncidentReportsOutput",
    "ImageAnalysisTool",
    "ImageAnalysisInput",
    "ImageAnalysisOutput",
    "GeolocationTool",
    "GeolocationInput",
    "GeolocationOutput",
    "RoutingTool",
    "RoutingInput",
    "RoutingOutput",
    "ResourceSearchTool",
    "ResourceSearchInput",
    "ResourceSearchOutput",
    "HospitalStatusTool",
    "HospitalStatusInput",
    "HospitalStatusOutput",
    "NotificationsTool",
    "NotificationInput",
    "NotificationOutput",
    "AmbulanceReservationTool",
    "AmbulanceReservationInput",
    "AmbulanceReservationOutput",
    "IncidentStatusUpdateTool",
    "IncidentStatusUpdateInput",
    "IncidentStatusUpdateOutput",
    "AuditLoggingTool",
    "AuditLogInput",
    "AuditLogOutput",
]
