"""NEXUS Tools Re-export Module (for backward compatibility).

Re-exports schemas, interfaces, mock providers, implementations, and registry.
"""

from __future__ import annotations

from tools.implementations import (
    AmbulanceReservationTool,
    AuditLoggingTool,
    GeolocationTool,
    HospitalStatusTool,
    ImageAnalysisTool,
    IncidentReportsTool,
    IncidentStatusUpdateTool,
    NotificationsTool,
    ResourceSearchTool,
    RoutingTool,
    WeatherTool,
)
from tools.interfaces import (
    AmbulanceReservationProvider,
    AuditLogProvider,
    GeolocationProvider,
    HospitalStatusProvider,
    ImageAnalysisProvider,
    IncidentReportsProvider,
    IncidentStatusProvider,
    NotificationProvider,
    ResourceSearchProvider,
    RoutingProvider,
    WeatherProvider,
)
from tools.mock_providers import (
    MockAmbulanceReservationProvider,
    MockAuditLogProvider,
    MockGeolocationProvider,
    MockHospitalStatusProvider,
    MockImageAnalysisProvider,
    MockIncidentReportsProvider,
    MockIncidentStatusProvider,
    MockNotificationProvider,
    MockResourceSearchProvider,
    MockRoutingProvider,
    MockWeatherProvider,
)
from tools.registry import (
    ToolRegistry,
    default_tool_registry,
    register_default_tools,
)
from tools.schemas import (
    SIMULATION_ENVIRONMENT_TAG,
    AmbulanceReservationInput,
    AmbulanceReservationOutput,
    AuditLogInput,
    AuditLogOutput,
    GeolocationInput,
    GeolocationOutput,
    HospitalStatusInput,
    HospitalStatusOutput,
    ImageAnalysisInput,
    ImageAnalysisOutput,
    IncidentReportItem,
    IncidentReportsInput,
    IncidentReportsOutput,
    IncidentStatusUpdateInput,
    IncidentStatusUpdateOutput,
    NotificationInput,
    NotificationOutput,
    ResourceSearchInput,
    ResourceSearchOutput,
    ResourceSummaryItem,
    RoutingInput,
    RoutingOutput,
    WeatherInput,
    WeatherOutput,
)

ENVIRONMENT_IDENTIFIER = SIMULATION_ENVIRONMENT_TAG
register_all_nexus_tools = register_default_tools

__all__ = [
    "ENVIRONMENT_IDENTIFIER",
    "SIMULATION_ENVIRONMENT_TAG",
    "register_all_nexus_tools",
    "register_default_tools",
    "ToolRegistry",
    "default_tool_registry",
    # Tools
    "WeatherTool",
    "IncidentReportsTool",
    "ImageAnalysisTool",
    "GeolocationTool",
    "RoutingTool",
    "ResourceSearchTool",
    "HospitalStatusTool",
    "NotificationsTool",
    "AmbulanceReservationTool",
    "IncidentStatusUpdateTool",
    "AuditLoggingTool",
    # Schemas
    "WeatherInput",
    "WeatherOutput",
    "IncidentReportsInput",
    "IncidentReportsOutput",
    "IncidentReportItem",
    "ImageAnalysisInput",
    "ImageAnalysisOutput",
    "GeolocationInput",
    "GeolocationOutput",
    "RoutingInput",
    "RoutingOutput",
    "ResourceSearchInput",
    "ResourceSearchOutput",
    "ResourceSummaryItem",
    "HospitalStatusInput",
    "HospitalStatusOutput",
    "NotificationInput",
    "NotificationOutput",
    "AmbulanceReservationInput",
    "AmbulanceReservationOutput",
    "IncidentStatusUpdateInput",
    "IncidentStatusUpdateOutput",
    "AuditLogInput",
    "AuditLogOutput",
    # Providers
    "WeatherProvider",
    "MockWeatherProvider",
    "IncidentReportsProvider",
    "MockIncidentReportsProvider",
    "ImageAnalysisProvider",
    "MockImageAnalysisProvider",
    "GeolocationProvider",
    "MockGeolocationProvider",
    "RoutingProvider",
    "MockRoutingProvider",
    "ResourceSearchProvider",
    "MockResourceSearchProvider",
    "HospitalStatusProvider",
    "MockHospitalStatusProvider",
    "NotificationProvider",
    "MockNotificationProvider",
    "AmbulanceReservationProvider",
    "MockAmbulanceReservationProvider",
    "IncidentStatusProvider",
    "MockIncidentStatusProvider",
    "AuditLogProvider",
    "MockAuditLogProvider",
]
